---
title: Jekyll PWA Starter
timezone: UTC
destination: _site/
domainname: no name
baseurl: /
sitename: My Website
assetsurl: /static-assets/
markdown: kramdown
highlighter: rouge
exclude:
- config
- screenshots
- node_modules
- gulpfile.js
- package.json
- src
- README.md
- Gemfile
- Gemfile.lock
- Dockerfile
- docker-entrypoint.sh
port: 4000
plugins_dir:
- jekyll-language-plugin
sass:
  style: :compressed

# front matter defaults for pages and posts. These fields are also available for editing in the Jekyll Admin GUI. This is available at localhost:4000/admin
defaults:
  -
    scope:
      path: ""
    values:
      all: true
  - scope:
      path: ''
      type: pages
    values:
      page_only: true
      layout: standard
  - scope:
      path: ''
      type: posts
    values:
      layout: posts
      short-desc: short desciption of your post.

languages: ['en', 'fr']
language_data: data.i18n.lang.%%
language_includes_dir: _i18n
